### ISSUE TITLE
CERES *STRUCTURES OUTPUT SHOWING JUST HALF OF THE CEREBELLUM

### ISSUE THREAD

**Issue by chiarabe1974** [volBrain/platform#4] opened 2024-03-22 19:05 UTC
Sorry to bother the team, but i am just becoming familiar with VolBrain pipeline, Ceres in particular. I have submitted my T1 images and i have downloaded the output as planned. Concerning the output everything seems to be fine, more or less, except that for the structures output, only the right hemisphere is shown. This applies to all mni_strutures* images i have. Images for cortical thickness and tissues are ok.

Where am i wrong?

I am working on a windows 11 system, browser is firefox (but the issue actually is visible outside a web browser, on visualization softwares like ITKsnap or MRICROGL

![1](https://github.com/volBrain/platform/assets/139698627/55770afc-82fe-4102-beb0-3cda68b4f8d3)
![2](https://github.com/volBrain/platform/assets/139698627/b03ddb72-280f-49ec-96b8-1de2e68b5c86)
![3](https://github.com/volBrain/platform/assets/139698627/d413e4e4-3986-4779-8ea2-95e993d04cc5)

**Comment by jmanjon** [comment] 2024-03-22 20:27
Left is there, but label numbers are low and look like background.
I suggest to see them with itksnap as segmentations.

**Comment by chiarabe1974** [comment] 2024-03-22 20:39
The issue is not visualization: the first image is obtained with ITKsnap and left is there. The issue is when i use the same images outside volbrain or ITKsnap...left just disappears. I've run also some analyses with SPM and the left hemisphere is not there at all...as if it had very low values to distort all the results of statistical analyses.

**Comment by chiarabe1974** [comment] 2024-03-22 20:41
anyways, this is how the segmentation looks like in ITKsnap
![immagine](https://github.com/volBrain/platform/assets/139698627/59fdf46f-bae6-4971-8980-563d2326b686)

**Comment by jmanjon** [comment] 2024-03-22 22:30
I can see the left in dark. I repeat. There is nothing wrong. This is a label map not an image.

**Comment by pierrickvolbrain** [comment] 2024-03-24 08:53
You have first to open your T1 mri and then add as segmentation layer the segmentation. On ITKsnap, first open your T1 as main image and then the segmentation as segmentation. Your issue is not issue, you just open a segmentation as image and since the labels between left and right have a shift of 100, they are dark. Please, close this issue which is not a bug.

**Closed as completed** 2024-03-24 12:07 UTC
Labels: bug
